# Generated by Django 5.1.1 on 2024-09-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_site', '0002_alter_produto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
