# Generated by Django 5.1.1 on 2024-09-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_site', '0003_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='agro_site/static/agro_site/images/'),
        ),
    ]
