# Generated by Django 5.1.1 on 2024-09-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_site', '0004_alter_produto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoAll',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='agro_site/static/agro_site/images/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
